### ISSUE TITLE
USTVGO Plugin

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_plugin_origin_USTVGO#11]
I am not able to stream any channels from the USTVGO plugin and I am not getting any errors in the logs. I have no problems with Pluto, Xumo or ToonamiAftermath. Stirr doesn't appear to be working either.

**Comment by Protektor-Desura** [comment]
I figured out what might be the problem. When it goes to pull channels I am getting this error.

AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxProfile'

**Comment by deathbybandaid** [comment]
seleniumwire is a terrible way to gather information for channels and channel streams. if ustvgo had a better api, this wouldn't be an issue.

**Comment by jerrymolenaar** [comment]
I am having the same issue.   I just installed fHDHR and got Pluto to work with no issues, but for USTVGO, I get the attached whenever I make a request for a channel.
[USTVGO Error.txt](https://github.com/fHDHR/fHDHR_plugin_origin_USTVGO/files/6218473/USTVGO.Error.txt)

**Comment by Protektor-Desura** [comment]
Does anyone know how to fix the no 'FirefoxProfile' error? Is there something else that needs to be installed?

**Comment by jerrymolenaar** [comment]
I did finally get it to work.   I did two things - not sure which fixed it.
1. I logged into Firefox which would have created a profile for me
2. I followed the steps in answer 2 on this link: https://stackoverflow.com/questions/57870311/how-to-properly-use-selenium-with-geckodriver-and-firefox-with-python-on-ubuntu

**Comment by Protektor-Desura** [comment]
I installed the geckodriver and that didn't fix my ability to stream a channel. I suspect I need a firefox profile setup?
