### ISSUE TITLE
Cannot stream any channel

### ISSUE THREAD

**Issue by dcardin** [fHDHR/fHDHR_plugin_origin_USTVGO#12]
I am getting this in the logs: 
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=nssFailure2&u=https%3A//ustvgo.tv/CBS&c=UTF-8&d=The%20connection%20to%20the%20server%20was%20reset%20while%20the%20page%20was%20loading.

Is it a new problem with ustvgo?
Thanks!

**Comment by deathbybandaid** [comment]
Most likely, it's what happens when you try to work around systems without proper api

**Comment by dcardin** [comment]
Yeah I suppose so, @deathbybandaid
I haven't had a chance to look at the code yet. Did it use to have a direct stream url? Seems like it's a little javascript app now.

**Comment by deathbybandaid** [comment]
it's been a while since I've looked at the code for this one (life got busy). But I believe I was able to get an m3u8 playlist url.

**Comment by deathbybandaid** [comment]
Now that Locast has killed it's service, I'm glad I ventured into a modular system that could use other services.

Locast2Tuner and Locast2Plex users might start migrating over to fHDHR, and hopefully I can get some help writing these origin plugins as well as documenting features.

**Comment by dcardin** [comment]
You absolutely took the best possible approach. I got stuck in the https://github.com/deathbybandaid/fHDHR_Locast void before realizing you had done that. Kudos. Found a problem with the filtering for iptv. I assume you welcome PRs ?

**Comment by deathbybandaid** [comment]
I do accept PRs! my original goal was to create a platform that could be extended easily. The main repo also has some stalebot-closed ideas for new origins as well.
