### ISSUE TITLE
USTVGO w/o needing browser

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_plugin_origin_USTVGO#13]
I think you should look at this script for how they do USTVGO M3U since it is pure Python and doesn't rely on a web browser or anything to work. It would solve the problem of working in a docker.

https://github.com/benmoose39/ustvgo_to_m3u

One thing to note is that the channels are keyed so you need to generate a new M3U every 8 hours.

**Comment by jerrymolenaar** [comment]
I understand that.   The previous version of USTVGO worked on all of the channels I mentioned.   The new version you posted this morning didn't work on those couple of channels.   When I reverted to the previous version, they worked again.

**Comment by deathbybandaid** [comment]
the old method has a very flawed way to using a browser to "click" buttons on the webpage, and in my experience was worse. I personally haven't used this plugin much because of this.

PRs are welcome for additional methods of retrieving the m3u8, that aren't "hacky"

**Comment by deathbybandaid** [comment]
@jerrymolenaar I think I may have found the issue.

Via the VLC plugin, and the built-in direct play modes, I'm seeing a TLS handshake issue with the domain.

However, the ffmpeg plugin is able to tune these.
