### ISSUE TITLE
FHDHR_USTVGo Timezone problem

### ISSUE THREAD

**Issue by s66jones** [fHDHR/fHDHR_plugin_origin_USTVGO#15]
I am in CST using the origin_USTVGO and HDHR plugins to import the video into plex. My guide in plex is showing the right time but the content is from 6 hours later. Example Jimmy Kimmel starts at 10:30 local time, but the guide is showing it is on at 4:30. Time is correct on my server.

**Comment by deathbybandaid** [comment]
I don't remember offhand, and I'm just checking my email,,,,


But I think that epg methods have the option to set a config of xmltv_offset or something like that

**Comment by s66jones** [comment]
Exactly what I was looking for, thank you very much.
