### ISSUE TITLE
fHDHR_USTVGO - Connection Closed: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by s66jones** [fHDHR/fHDHR_plugin_origin_USTVGO#16]
Some channels are pulling up just fine through fHDHR, and some never load. These are not channels that require the vpn and I can view them directly through ustvgo.tv. When looking at the logs I see Connection Closed: HTTP Error 404: Not Found. I run a channel update but it doesn't change the URL. Any ideas?

Nov 12 12:43:32 JThink python3[31190]: [2021-11-12 18:43:32,066] INFO - Connection Closed: HTTP Error 404: Not Found
Nov 12 12:43:32 JThink python3[31190]: [2021-11-12 18:43:32,078] INFO - Detected stream of m3u8 URL: https://h3.ustvgo.la/COMEDY/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTEvMTIvMjAyMSA2OjMxOjI4IFBNJmhhc2hfdmFsdWU9LzdHRkVHVmxUSFAreHhueEpSRXNuUT09JnZhbGlkbWludXRlcz0yNDA=

**Comment by deathbybandaid** [comment]
Their api is half-assed

**Comment by s66jones** [comment]
What I was scared of. If I pull the correct url from devtools, is there a way I can update it in the fhdhr database?

**Comment by deathbybandaid** [comment]
I recently switched the methodology of this plugin to use the actual API, you can look at the old method which mightbhave different channel support

**Comment by deathbybandaid** [comment]
Also, if I remember correctly, their api is via a php script
